### PR TITLE
 Use new recipe conventions and some updates

### PR DESCRIPTION
**Pull request by danimtb**
- Get license from header of a file (GPLv3)
- Use ConanInvalidConfiguration
- Removed cmake_configure()

### CODE REVIEW

**Comment by danimtb** [comment]
cc/ @SSE4

**Comment by danimtb** [comment]
Please remember to backport this changes to 2.5.25 version when merged

**Review by SSE4 — APPROVED** [review]

**Comment by Croydon** [comment]
Bison is GPLv3 and Flex is some (I believe modified version) BSD license. That's why I added "several licenses"....

**Comment by SSE4** [comment]
backported to 2.5.15

**Comment by danimtb** [comment]
@Croydon you are right. I also saw some of the license header in the flex files are GPL and thought about using the "most restrictive" one. Feel free to change it but please include a license file in the packages 📁

**Pull request merged**
